global:
  environment: dev
  namespace: lbg-ns

patientService:
  name: patient-service
  replicaCount: 2
  image: patient-service
  tag: latest
  port: 3000
  serviceType: ClusterIP
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "100m"
  hpa:
    minReplicas: 1
    maxReplicas: 5
    targetCPU: 50
    targetMemory: 70

appointmentService:
  name: appointment-service
  replicaCount: 2
  image: appointment-service
  tag: latest
  port: 3001
  serviceType: ClusterIP
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "100m"
  hpa:
    minReplicas: 1
    maxReplicas: 5
    targetCPU: 50
    targetMemory: 70

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "30"
  hosts:
    - host: lbg-app.dev.local
      paths:
        - path: /patients
          pathType: Prefix
        - path: /appointments
          pathType: Prefix
        - path: /health
          pathType: Prefix
        - path: /
          pathType: Prefix

persistence:
  enabled: false
  size: 1Gi
  storageClass: "default"

image:
  registry: acrlbgdemodev2025.azurecr.io
  pullPolicy: IfNotPresent
  credentials:
    secretName: acrlbgdemodev2025-secret
