global:
  namespace: lbg-ns
  environment: dev
  
image:
  registry: acrlbgdemodev2025.azurecr.io
  pullPolicy: IfNotPresent

patientService:
  name: patient-service
  replicaCount: 2
  image: patient-service
  tag: latest
  port: 3000
  serviceType: ClusterIP
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "100m"
  hpa:
    minReplicas: 1
    maxReplicas: 5
    targetCPU: 50
    targetMemory: 70

appointmentService:
  name: appointment-service
  replicaCount: 2
  image: appointment-service
  tag: latest
  port: 3001
  serviceType: ClusterIP
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "100m"
  hpa:
    minReplicas: 1
    maxReplicas: 5
    targetCPU: 50
    targetMemory: 70

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  hosts:
    - host: lbg-app.dev.local
      paths:
        - path: /
          pathType: Prefix
        - path: /patients
          pathType: Prefix
        - path: /appointments
          pathType: Prefix

persistence:
  enabled: false